print("Hello World")
print("  *")
print(" ****")
print("******")
print("bhargavi\'s")
print("bhargavi\"s")
n1=(input("enter num:"))
n2=(input("enter another num:"))
print(n1+" "+n2)
#print("n1 is "+ str(n1))
string="hello\tboss"
#print(string.upper().isupper())
print(len(string))
list1=['aaa','bbbb','ccc','ddd']
list2=['eee']
list1.append("iii")
list1.extend(list2)
list1.insert(2,'oo')
list1.remove("aaa")
list1.pop()
list3=list1.copy()
print(list3)
print(list3.count('bbbb'))
print("index of ccc is "+str(list1.index("ccc")))
list1.reverse()
print(list1)
